@backend_HostAddress = http://localhost:5179

###
# Install app
POST {{backend_HostAddress}}/connector/github/webhook/
Accept: */*
Content-Type: application/json
User-Agent: GitHub-Hookshot/5cc3d7d
X-GitHub-Delivery: 731706e0-5be6-11f0-9d19-11c41edfbbdf
X-GitHub-Event: installation
X-GitHub-Hook-ID: 550008922
X-GitHub-Hook-Installation-Target-ID: 1284025
X-GitHub-Hook-Installation-Target-Type: integration
X-Hub-Signature: sha1=9ad727713947953e514881a4c6f9fa3e21d86591
X-Hub-Signature-256: sha256={{signatures_installation_created}}

{
  "action": "created",
  "installation": {
    "id": 74897782,
    "client_id": "Iv23liPsdCfdNm8BxDGt",
    "account": {
      "login": "glutenfreemap",
      "id": 121765459,
      "node_id": "O_kgDOB0H-Uw",
      "avatar_url": "https://avatars.githubusercontent.com/u/121765459?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/glutenfreemap",
      "html_url": "https://github.com/glutenfreemap",
      "followers_url": "https://api.github.com/users/glutenfreemap/followers",
      "following_url": "https://api.github.com/users/glutenfreemap/following{/other_user}",
      "gists_url": "https://api.github.com/users/glutenfreemap/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/glutenfreemap/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/glutenfreemap/subscriptions",
      "organizations_url": "https://api.github.com/users/glutenfreemap/orgs",
      "repos_url": "https://api.github.com/users/glutenfreemap/repos",
      "events_url": "https://api.github.com/users/glutenfreemap/events{/privacy}",
      "received_events_url": "https://api.github.com/users/glutenfreemap/received_events",
      "type": "Organization",
      "user_view_type": "public",
      "site_admin": false
    },
    "repository_selection": "selected",
    "access_tokens_url": "https://api.github.com/app/installations/74897782/access_tokens",
    "repositories_url": "https://api.github.com/installation/repositories",
    "html_url": "https://github.com/organizations/glutenfreemap/settings/installations/74897782",
    "app_id": 1284025,
    "app_slug": "glutenfreemap-connector",
    "target_id": 121765459,
    "target_type": "Organization",
    "permissions": {
      "contents": "write",
      "metadata": "read"
    },
    "events": [
      "push"
    ],
    "created_at": "2025-07-08T11:29:37.000+01:00",
    "updated_at": "2025-07-08T11:29:38.000+01:00",
    "single_file_name": null,
    "has_multiple_single_files": false,
    "single_file_paths": [

    ],
    "suspended_by": null,
    "suspended_at": null
  },
  "repositories": [
    {
      "id": 945492266,
      "node_id": "R_kgDOOFsRKg",
      "name": "data-portugal",
      "full_name": "glutenfreemap/data-portugal",
      "private": true
    }
  ],
  "requester": null,
  "sender": {
    "login": "aaubry",
    "id": 630495,
    "node_id": "MDQ6VXNlcjYzMDQ5NQ==",
    "avatar_url": "https://avatars.githubusercontent.com/u/630495?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/aaubry",
    "html_url": "https://github.com/aaubry",
    "followers_url": "https://api.github.com/users/aaubry/followers",
    "following_url": "https://api.github.com/users/aaubry/following{/other_user}",
    "gists_url": "https://api.github.com/users/aaubry/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/aaubry/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/aaubry/subscriptions",
    "organizations_url": "https://api.github.com/users/aaubry/orgs",
    "repos_url": "https://api.github.com/users/aaubry/repos",
    "events_url": "https://api.github.com/users/aaubry/events{/privacy}",
    "received_events_url": "https://api.github.com/users/aaubry/received_events",
    "type": "User",
    "user_view_type": "public",
    "site_admin": false
  }
}

###
# Uninstall the application
POST {{backend_HostAddress}}/connector/github/webhook/
Accept: */*
Content-Type: application/json
User-Agent: GitHub-Hookshot/5cc3d7d
X-GitHub-Delivery: 67fca9fa-5be5-11f0-9403-3b5d74ed7ac3
X-GitHub-Event: installation
X-GitHub-Hook-ID: 550008922
X-GitHub-Hook-Installation-Target-ID: 1284025
X-GitHub-Hook-Installation-Target-Type: integration
X-Hub-Signature: sha1=0190dc7732cba5eaa17e20b9dd2f051757d0a2d6
X-Hub-Signature-256: sha256={{signatures_installation_deleted}}

{
  "action": "deleted",
  "installation": {
    "id": 74897782,
    "client_id": "Iv23liPsdCfdNm8BxDGt",
    "account": {
      "login": "glutenfreemap",
      "id": 121765459,
      "node_id": "O_kgDOB0H-Uw",
      "avatar_url": "https://avatars.githubusercontent.com/u/121765459?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/glutenfreemap",
      "html_url": "https://github.com/glutenfreemap",
      "followers_url": "https://api.github.com/users/glutenfreemap/followers",
      "following_url": "https://api.github.com/users/glutenfreemap/following{/other_user}",
      "gists_url": "https://api.github.com/users/glutenfreemap/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/glutenfreemap/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/glutenfreemap/subscriptions",
      "organizations_url": "https://api.github.com/users/glutenfreemap/orgs",
      "repos_url": "https://api.github.com/users/glutenfreemap/repos",
      "events_url": "https://api.github.com/users/glutenfreemap/events{/privacy}",
      "received_events_url": "https://api.github.com/users/glutenfreemap/received_events",
      "type": "Organization",
      "user_view_type": "public",
      "site_admin": false
    },
    "repository_selection": "selected",
    "access_tokens_url": "https://api.github.com/app/installations/74897782/access_tokens",
    "repositories_url": "https://api.github.com/installation/repositories",
    "html_url": "https://github.com/organizations/glutenfreemap/settings/installations/74897782",
    "app_id": 1284025,
    "app_slug": "glutenfreemap-connector",
    "target_id": 121765459,
    "target_type": "Organization",
    "permissions": {
      "contents": "write",
      "metadata": "read"
    },
    "events": [
      "push"
    ],
    "created_at": "2025-06-02T17:12:51.000+01:00",
    "updated_at": "2025-07-08T10:43:25.000+01:00",
    "single_file_name": null,
    "has_multiple_single_files": false,
    "single_file_paths": [

    ],
    "suspended_by": null,
    "suspended_at": null
  },
  "repositories": [
    {
      "id": 945492266,
      "node_id": "R_kgDOOFsRKg",
      "name": "data-portugal",
      "full_name": "glutenfreemap/data-portugal",
      "private": true
    }
  ],
  "sender": {
    "login": "aaubry",
    "id": 630495,
    "node_id": "MDQ6VXNlcjYzMDQ5NQ==",
    "avatar_url": "https://avatars.githubusercontent.com/u/630495?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/aaubry",
    "html_url": "https://github.com/aaubry",
    "followers_url": "https://api.github.com/users/aaubry/followers",
    "following_url": "https://api.github.com/users/aaubry/following{/other_user}",
    "gists_url": "https://api.github.com/users/aaubry/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/aaubry/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/aaubry/subscriptions",
    "organizations_url": "https://api.github.com/users/aaubry/orgs",
    "repos_url": "https://api.github.com/users/aaubry/repos",
    "events_url": "https://api.github.com/users/aaubry/events{/privacy}",
    "received_events_url": "https://api.github.com/users/aaubry/received_events",
    "type": "User",
    "user_view_type": "public",
    "site_admin": false
  }
}

###
# Push
POST {{backend_HostAddress}}/connector/github/webhook/
Accept: */*
Content-Type: application/json
User-Agent: GitHub-Hookshot/5cc3d7d
X-GitHub-Delivery: cacd9aa6-5be7-11f0-8c10-c94c70bb44ce
X-GitHub-Event: push
X-GitHub-Hook-ID: 550008922
X-GitHub-Hook-Installation-Target-ID: 1284025
X-GitHub-Hook-Installation-Target-Type: integration
X-Hub-Signature: sha1=c2dbd7f08e20588ffc85da7e2de2251812aff0b3
X-Hub-Signature-256: sha256={{signatures_push}}

{
  "ref": "refs/heads/master",
  "before": "724f9937d9aed2362d7a0a5d1a7e896af45af914",
  "after": "c295959a42a0c92ff8e28c22bb0f8a64baffb54a",
  "repository": {
    "id": 945492266,
    "node_id": "R_kgDOOFsRKg",
    "name": "data-portugal",
    "full_name": "glutenfreemap/data-portugal",
    "private": true,
    "owner": {
      "name": "glutenfreemap",
      "email": null,
      "login": "glutenfreemap",
      "id": 121765459,
      "node_id": "O_kgDOB0H-Uw",
      "avatar_url": "https://avatars.githubusercontent.com/u/121765459?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/glutenfreemap",
      "html_url": "https://github.com/glutenfreemap",
      "followers_url": "https://api.github.com/users/glutenfreemap/followers",
      "following_url": "https://api.github.com/users/glutenfreemap/following{/other_user}",
      "gists_url": "https://api.github.com/users/glutenfreemap/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/glutenfreemap/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/glutenfreemap/subscriptions",
      "organizations_url": "https://api.github.com/users/glutenfreemap/orgs",
      "repos_url": "https://api.github.com/users/glutenfreemap/repos",
      "events_url": "https://api.github.com/users/glutenfreemap/events{/privacy}",
      "received_events_url": "https://api.github.com/users/glutenfreemap/received_events",
      "type": "Organization",
      "user_view_type": "public",
      "site_admin": false
    },
    "html_url": "https://github.com/glutenfreemap/data-portugal",
    "description": "Dados de Portugal",
    "fork": false,
    "url": "https://api.github.com/repos/glutenfreemap/data-portugal",
    "forks_url": "https://api.github.com/repos/glutenfreemap/data-portugal/forks",
    "keys_url": "https://api.github.com/repos/glutenfreemap/data-portugal/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/glutenfreemap/data-portugal/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/glutenfreemap/data-portugal/teams",
    "hooks_url": "https://api.github.com/repos/glutenfreemap/data-portugal/hooks",
    "issue_events_url": "https://api.github.com/repos/glutenfreemap/data-portugal/issues/events{/number}",
    "events_url": "https://api.github.com/repos/glutenfreemap/data-portugal/events",
    "assignees_url": "https://api.github.com/repos/glutenfreemap/data-portugal/assignees{/user}",
    "branches_url": "https://api.github.com/repos/glutenfreemap/data-portugal/branches{/branch}",
    "tags_url": "https://api.github.com/repos/glutenfreemap/data-portugal/tags",
    "blobs_url": "https://api.github.com/repos/glutenfreemap/data-portugal/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/glutenfreemap/data-portugal/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/glutenfreemap/data-portugal/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/glutenfreemap/data-portugal/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/glutenfreemap/data-portugal/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/glutenfreemap/data-portugal/languages",
    "stargazers_url": "https://api.github.com/repos/glutenfreemap/data-portugal/stargazers",
    "contributors_url": "https://api.github.com/repos/glutenfreemap/data-portugal/contributors",
    "subscribers_url": "https://api.github.com/repos/glutenfreemap/data-portugal/subscribers",
    "subscription_url": "https://api.github.com/repos/glutenfreemap/data-portugal/subscription",
    "commits_url": "https://api.github.com/repos/glutenfreemap/data-portugal/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/glutenfreemap/data-portugal/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/glutenfreemap/data-portugal/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/glutenfreemap/data-portugal/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/glutenfreemap/data-portugal/contents/{+path}",
    "compare_url": "https://api.github.com/repos/glutenfreemap/data-portugal/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/glutenfreemap/data-portugal/merges",
    "archive_url": "https://api.github.com/repos/glutenfreemap/data-portugal/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/glutenfreemap/data-portugal/downloads",
    "issues_url": "https://api.github.com/repos/glutenfreemap/data-portugal/issues{/number}",
    "pulls_url": "https://api.github.com/repos/glutenfreemap/data-portugal/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/glutenfreemap/data-portugal/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/glutenfreemap/data-portugal/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/glutenfreemap/data-portugal/labels{/name}",
    "releases_url": "https://api.github.com/repos/glutenfreemap/data-portugal/releases{/id}",
    "deployments_url": "https://api.github.com/repos/glutenfreemap/data-portugal/deployments",
    "created_at": 1741532174,
    "updated_at": "2025-05-04T16:15:14Z",
    "pushed_at": 1751971154,
    "git_url": "git://github.com/glutenfreemap/data-portugal.git",
    "ssh_url": "git@github.com:glutenfreemap/data-portugal.git",
    "clone_url": "https://github.com/glutenfreemap/data-portugal.git",
    "svn_url": "https://github.com/glutenfreemap/data-portugal",
    "homepage": null,
    "size": 226,
    "stargazers_count": 0,
    "watchers_count": 0,
    "language": null,
    "has_issues": false,
    "has_projects": false,
    "has_downloads": true,
    "has_wiki": false,
    "has_pages": false,
    "has_discussions": false,
    "forks_count": 0,
    "mirror_url": null,
    "archived": false,
    "disabled": false,
    "open_issues_count": 0,
    "license": {
      "key": "cc-by-sa-4.0",
      "name": "Creative Commons Attribution Share Alike 4.0 International",
      "spdx_id": "CC-BY-SA-4.0",
      "url": "https://api.github.com/licenses/cc-by-sa-4.0",
      "node_id": "MDc6TGljZW5zZTI2"
    },
    "allow_forking": false,
    "is_template": false,
    "web_commit_signoff_required": false,
    "topics": [

    ],
    "visibility": "private",
    "forks": 0,
    "open_issues": 0,
    "watchers": 0,
    "default_branch": "master",
    "stargazers": 0,
    "master_branch": "master",
    "organization": "glutenfreemap",
    "custom_properties": {

    }
  },
  "pusher": {
    "name": "aaubry",
    "email": "antoine@aaubry.net"
  },
  "organization": {
    "login": "glutenfreemap",
    "id": 121765459,
    "node_id": "O_kgDOB0H-Uw",
    "url": "https://api.github.com/orgs/glutenfreemap",
    "repos_url": "https://api.github.com/orgs/glutenfreemap/repos",
    "events_url": "https://api.github.com/orgs/glutenfreemap/events",
    "hooks_url": "https://api.github.com/orgs/glutenfreemap/hooks",
    "issues_url": "https://api.github.com/orgs/glutenfreemap/issues",
    "members_url": "https://api.github.com/orgs/glutenfreemap/members{/member}",
    "public_members_url": "https://api.github.com/orgs/glutenfreemap/public_members{/member}",
    "avatar_url": "https://avatars.githubusercontent.com/u/121765459?v=4",
    "description": "Manages the GlutenFreeMap application"
  },
  "sender": {
    "login": "aaubry",
    "id": 630495,
    "node_id": "MDQ6VXNlcjYzMDQ5NQ==",
    "avatar_url": "https://avatars.githubusercontent.com/u/630495?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/aaubry",
    "html_url": "https://github.com/aaubry",
    "followers_url": "https://api.github.com/users/aaubry/followers",
    "following_url": "https://api.github.com/users/aaubry/following{/other_user}",
    "gists_url": "https://api.github.com/users/aaubry/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/aaubry/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/aaubry/subscriptions",
    "organizations_url": "https://api.github.com/users/aaubry/orgs",
    "repos_url": "https://api.github.com/users/aaubry/repos",
    "events_url": "https://api.github.com/users/aaubry/events{/privacy}",
    "received_events_url": "https://api.github.com/users/aaubry/received_events",
    "type": "User",
    "user_view_type": "public",
    "site_admin": false
  },
  "installation": {
    "id": 74897782,
    "node_id": "MDIzOkludGVncmF0aW9uSW5zdGFsbGF0aW9uNzQ4OTc3ODI="
  },
  "created": false,
  "deleted": false,
  "forced": false,
  "base_ref": null,
  "compare": "https://github.com/glutenfreemap/data-portugal/compare/724f9937d9ae...14cc9ce490b7",
  "commits": [
    {
      "id": "14cc9ce490b7640d5d9794f374b9978ad217dd82",
      "tree_id": "5e819fe205cc44a62cc6b6953bcafd77ae7eb694",
      "distinct": true,
      "message": "Update a-melhor.json",
      "timestamp": "2025-07-08T11:39:14+01:00",
      "url": "https://github.com/glutenfreemap/data-portugal/commit/14cc9ce490b7640d5d9794f374b9978ad217dd82",
      "author": {
        "name": "Antoine Aubry",
        "email": "antoine@aaubry.net",
        "username": "aaubry"
      },
      "committer": {
        "name": "GitHub",
        "email": "noreply@github.com",
        "username": "web-flow"
      },
      "added": [

      ],
      "removed": [

      ],
      "modified": [
        "places/a-melhor.json"
      ]
    }
  ],
  "head_commit": {
    "id": "14cc9ce490b7640d5d9794f374b9978ad217dd82",
    "tree_id": "5e819fe205cc44a62cc6b6953bcafd77ae7eb694",
    "distinct": true,
    "message": "Update a-melhor.json",
    "timestamp": "2025-07-08T11:39:14+01:00",
    "url": "https://github.com/glutenfreemap/data-portugal/commit/14cc9ce490b7640d5d9794f374b9978ad217dd82",
    "author": {
      "name": "Antoine Aubry",
      "email": "antoine@aaubry.net",
      "username": "aaubry"
    },
    "committer": {
      "name": "GitHub",
      "email": "noreply@github.com",
      "username": "web-flow"
    },
    "added": [

    ],
    "removed": [

    ],
    "modified": [
      "places/a-melhor.json"
    ]
  }
}

###
GET {{backend_HostAddress}}/repos

###
GET {{backend_HostAddress}}/repos/github/glutenfreemap/data-portugal/tree

###
GET {{backend_HostAddress}}/repos/github/glutenfreemap/data-portugal/tree
If-None-Match: "513e7700c6ea40cb864832e66d47826c"

###
POST {{backend_HostAddress}}/test/github/glutenfreemap/data-portugal/invalidate

###
GET {{backend_HostAddress}}/repos/github/glutenfreemap/data-portugal/places/grom.json

###
GET {{backend_HostAddress}}/repos/github/glutenfreemap/data-portugal/blobs/0015898ae4d534d215a9ef8bef8e41f22aad6a8a


