name: Update Burger King

on:
  workflow_dispatch: {}
  schedule:
    - cron: '34 8 * * *'

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Cache NuGet packages
        id: cache-nuget
        uses: actions/cache@v4
        with:
          path: utils/packages
          # An explicit key for restoring and saving the cache
          key: ${{ runner.os }}-nuget-${{ hashFiles('utils/packages.config') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Install mono
        if: steps.cache-nuget.outputs.cache-hit != 'true'
        run: |
          sudo apt-get update
          sudo apt-get install --no-install-recommends -y mono-complete

      - name: Setup NuGet.exe for use with actions
        if: steps.cache-nuget.outputs.cache-hit != 'true'
        uses: NuGet/setup-nuget@v2.0.0
              
      - name: Restore NuGet packages
        if: steps.cache-nuget.outputs.cache-hit != 'true'
        run: |
          cd utils
          nuget restore -PackagesDirectory packages

      - name: Run Update-BurgerKing.ps1 script
        run: |
          cd utils
          pwsh -File Update-BurgerKing.ps1

      - name: Check if file has changed
        id: check_changes
        run: |
          git diff --quiet -- site/data/burgerking.json || echo "changed=true" >> $GITHUB_OUTPUT

      - name: Commit and push changes
        if: steps.check_changes.outputs.changed == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -a -m "Update BurgerKing stores"
          git push
